# Generated by Django 2.2.3 on 2019-07-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic_number', '0003_auto_20190704_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='banner',
            field=models.ImageField(height_field=150, upload_to='magic_number/static/magic_number', width_field=150),
        ),
    ]
