# Generated by Django 2.2.3 on 2019-07-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic_number', '0004_auto_20190704_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='banner',
            field=models.ImageField(upload_to='magic_number/static/magic_number'),
        ),
    ]
