# Generated by Django 2.1.7 on 2019-03-17 06:53

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20190317_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_joined',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='date_joined',
            field=models.DateField(auto_created=True, default=datetime.datetime(2019, 3, 17, 6, 53, 23, 47443, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
