# Generated by Django 2.1.7 on 2019-03-17 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_auto_20190317_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student',
            new_name='project',
        ),
    ]
