# Generated by Django 2.1.7 on 2019-03-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_auto_20190317_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='region',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
