# Generated by Django 2.1.7 on 2019-03-17 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_auto_20190317_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.RegexValidator(message='年龄为18-99的数字', regex='^[18-99]')], verbose_name='年龄(18-99)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='region',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.SmallIntegerField(default=-1, verbose_name='性别(0女，1男，-1保密)'),
        ),
    ]
