# Generated by Django 2.2.3 on 2019-07-03 07:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_auto_20190317_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.SmallIntegerField(default=-1)),
                ('desc', models.CharField(max_length=512)),
                ('background', models.ImageField(upload_to='')),
                ('date_joined', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.SmallIntegerField(default=20, validators=[django.core.validators.RegexValidator(code='error age', message='年龄为18-99的数字', regex='^(1[8-9]|[2-9]\\d)$')], verbose_name='年龄(18-99)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(code='error phone style', message="手机号码格式为: '1xxxxxxxxxx'. Up to 11 digits allowed.", regex='^(1?\\d{10})$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.SmallIntegerField(choices=[(-1, '保密'), (1, '女'), (0, '男')], default=-1, verbose_name='性别'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.SmallIntegerField(default=-1)),
                ('time', models.DateField()),
                ('background', models.ImageField(upload_to='')),
                ('date_joined', models.DateField(auto_now=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.Teacher')),
            ],
        ),
    ]
